### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by falsetru** [sorinsi/djangorestframework-messagepack#1]
Install failed with following error.
```sh
$ pip install djangorestframework-messagepack
Collecting djangorestframework-messagepack
  Using cached djangorestframework-messagepack-1.0.0.tar.gz (2.5 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/falsetru/.virtualenvs/targetyo/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-njwv52h7/djangorestframework-messagepack/setup.py'"'"'; __file__='"'"'/tmp/pip-install-njwv52h7/djangorestframework-messagepack/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-503j1n6w
         cwd: /tmp/pip-install-njwv52h7/djangorestframework-messagepack/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-njwv52h7/djangorestframework-messagepack/setup.py", line 12, in <module>
        install_requires=open("requirements.txt").read().split("\n"),
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

- `djangorestframework-messagepack-1.0.0.tar.gz` does not include `requirements.txt`
- `setup.py` try to read the file. https://github.com/sorinsi/djangorestframework-messagepack/blob/0cc815d6600b73597c21d2680ac2ebb720fe5e14/setup.py#L12
```sh
$ tar tzf djangorestframework-messagepack-1.0.0.tar.gz
djangorestframework-messagepack-1.0.0/
djangorestframework-messagepack-1.0.0/PKG-INFO
djangorestframework-messagepack-1.0.0/README.md
djangorestframework-messagepack-1.0.0/djangorestframework_messagepack.egg-info/
djangorestframework-messagepack-1.0.0/djangorestframework_messagepack.egg-info/PKG-INFO
djangorestframework-messagepack-1.0.0/djangorestframework_messagepack.egg-info/SOURCES.txt
djangorestframework-messagepack-1.0.0/djangorestframework_messagepack.egg-info/dependency_links.txt
djangorestframework-messagepack-1.0.0/djangorestframework_messagepack.egg-info/requires.txt
djangorestframework-messagepack-1.0.0/djangorestframework_messagepack.egg-info/top_level.txt
djangorestframework-messagepack-1.0.0/rest_framework_messagepack/
djangorestframework-messagepack-1.0.0/rest_framework_messagepack/__init__.py
djangorestframework-messagepack-1.0.0/rest_framework_messagepack/encoders.py
djangorestframework-messagepack-1.0.0/rest_framework_messagepack/parsers.py
djangorestframework-messagepack-1.0.0/rest_framework_messagepack/renderers.py
djangorestframework-messagepack-1.0.0/setup.cfg
djangorestframework-messagepack-1.0.0/setup.py
```

**Comment by sorinsi** [comment]
Thank you for taking the time to post this issue. There was a misconfiguration issue and I solved it. Hope you have a nice day!
